version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx:/var/www
      - static_volume:/code/static_root
    links:
      - web

  pgbackups:
      image: prodrigestivill/postgres-backup-local
      restart: always
      volumes:
          - ./backups:/backups
      depends_on:
          - db
      env_file:
        - .env

  db:
    image: postgres:9.6.5
    env_file:
     - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"

  web:
    build: .
    command: bash -c "/usr/local/bin/gunicorn helpdesk.wsgi:application --bind 0.0.0.0:8000"
    env_file:
     - .env
    volumes:
      - .:/code
      - static_volume:/code/static_root
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  postgres_data:
  static_volume:
