# Generated by Django 3.0.2 on 2020-01-06 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('problem_description', models.TextField(default='')),
                ('priority', models.IntegerField(choices=[(1, 'High'), (2, 'Normal'), (3, 'Low')], null=True)),
                ('category', models.IntegerField(choices=[(1, 'Workstation'), (2, 'Laptop'), (3, 'Server'), (4, 'Network'), (5, 'Printer'), (6, 'Scanner'), (7, 'Other Peripheral'), (8, 'Software'), (9, 'Access')], null=True)),
                ('notes', models.TextField(default='')),
                ('resolution', models.TextField(default='')),
                ('status', models.IntegerField(choices=[(1, 'Open'), (2, 'Closed')], default=1)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
