# Generated by Django 3.0.2 on 2020-02-10 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0007_auto_20200207_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='tickets.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
