# Generated by Django 3.0.2 on 2020-02-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_auto_20200217_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverequestticket',
            name='new_room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='moverequestticket',
            name='old_room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
