# Generated by Django 3.0.2 on 2020-02-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_auto_20200218_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserticket',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
