# Generated by Django 3.0.2 on 2020-02-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_newuserticket_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserticket',
            name='needs_computer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newuserticket',
            name='needs_email_account',
            field=models.BooleanField(default=False),
        ),
    ]
