# Generated by Django 3.0.2 on 2020-02-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20200218_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserticket',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
