# Generated by Django 3.0.2 on 2020-02-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20200218_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='moverequestticket',
            name='name',
            field=models.CharField(default='Nobody', max_length=120),
            preserve_default=False,
        ),
    ]
