# Generated by Django 3.0.2 on 2020-02-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_moverequestticket_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='newuserticket',
            name='cms_access',
            field=models.IntegerField(choices=[(1, 'None Needed'), (2, 'Guest (Read Only)'), (3, 'DAStaff (Read and Write)')]),
        ),
        migrations.AlterField(
            model_name='moverequestticket',
            name='new_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_requests_to', to='tickets.Building'),
        ),
        migrations.AlterField(
            model_name='moverequestticket',
            name='new_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_requests_to', to='tickets.Division'),
        ),
        migrations.AlterField(
            model_name='moverequestticket',
            name='old_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_requests_from', to='tickets.Building'),
        ),
        migrations.AlterField(
            model_name='moverequestticket',
            name='old_division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='move_requests_from', to='tickets.Division'),
        ),
        migrations.AlterField(
            model_name='newuserticket',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Building'),
        ),
        migrations.AlterField(
            model_name='newuserticket',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.Division'),
        ),
        migrations.AlterField(
            model_name='newuserticket',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.JobTitle'),
        ),
    ]
